[package]
name = "reduced-c"
version = "0.1.0"
authors = ["Peter Marheine <peter@taricorp.net>"]

[profile.release]
lto = true

[lib]

[dependencies.reduced-c-syntax]
# In its own subcrate to avoid slow recompiles
path = "syntax"

[dependencies]
docopt = "1"
env_logger = "0.8"
log = "0.4"

